site_name: pySchieber
site_description: A tool to give runners an online presence
repo_url: https://github.com/Ziegelstein/pySchieber
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/Ziegelstein">Ziegelstein</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
